server:
  port: 8085

spring:
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      username: sqq
      password: sqq.-=5671
      url: jdbc:mysql://120.25.243.0:53251/spring_cloud_db?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true

#spring:
#  zipkin:
#    rabbitmq:
#      queue: zipkin
#  sleuth:
#    sampler:
#      percentage: 0.2



