server:
  port: 8085

spring:
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      password: 123456
      url: jdbc:mysql://127.0.0.1:3306/spring_cloud_db?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true

#spring:
#  zipkin:
#    rabbitmq:
#      queue: zipkin
#  sleuth:
#    sampler:
#      percentage: 0.2



